/**
 * Exports live Postgres schema (tables, views, indexes, RLS), function, and
 * trigger definitions from the local Supabase DB into db/sql/*.sql for local
 * inspection.
 *
 * Usage: pnpm db:export
 *
 * These files are generated and gitignored — do not commit them.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import pg from "pg";

const ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUTPUT_DIR = join(ROOT_DIR, "db", "sql");
const SCHEMA_PATH = join(OUTPUT_DIR, "schema.sql");
const FUNCTIONS_PATH = join(OUTPUT_DIR, "functions.sql");
const TRIGGERS_PATH = join(OUTPUT_DIR, "triggers.sql");

const DEFAULT_DATABASE_URL =
  "postgresql://postgres:postgres@127.0.0.1:54322/postgres";

const GENERATED_HEADER = `\
-- GENERATED FILE — do not put this in source control.
-- Regenerated by: pnpm db:export
-- Source: live local Supabase Postgres (pg_dump / pg_get_functiondef / pg_get_triggerdef)
`;

const SCHEMA_DUMP_ARGS = [
  "--schema-only",
  "--no-owner",
  "--no-privileges",
  "--schema=public",
];

/** pg_dump object types that mirror typical Drizzle/Supabase migration DDL. */
const SCHEMA_OBJECT_TYPES = new Set([
  "TYPE",
  "TABLE",
  "VIEW",
  "CONSTRAINT",
  "FK CONSTRAINT",
  "INDEX",
  "ROW SECURITY",
  "POLICY",
]);

const PG_DUMP_SECTION_HEADER_RE =
  /^-- Name: .+; Type: ([^;]+); Schema: [^;]*; Owner:.*$/;

const FUNCTIONS_QUERY = `
select
  p.proname as name,
  coalesce(pg_get_function_identity_arguments(p.oid), '') as args,
  pg_get_functiondef(p.oid) as definition
from pg_proc p
join pg_namespace n on n.oid = p.pronamespace
where n.nspname = 'public'
  and p.prokind in ('f', 'p', 'w')
  and not exists (
    select 1
    from pg_depend d
    join pg_extension e on e.oid = d.refobjid
    where d.objid = p.oid
      and d.deptype = 'e'
  )
order by p.proname, pg_get_function_identity_arguments(p.oid);
`;

const TRIGGERS_QUERY = `
select
  n.nspname as schema_name,
  c.relname as table_name,
  t.tgname as name,
  pg_get_triggerdef(t.oid, true) as definition
from pg_trigger t
join pg_class c on c.oid = t.tgrelid
join pg_namespace n on n.oid = c.relnamespace
where not t.tgisinternal
  and n.nspname in ('public', 'auth')
order by n.nspname, c.relname, t.tgname;
`;

/**
 * Builds a SQL dump file body from labeled definition rows.
 * @param {Array<{ label: string, definition: string }>} rows
 * @returns {string}
 */
function buildSqlDump(rows) {
  const parts = [GENERATED_HEADER, `\n-- Count: ${rows.length}\n`];

  for (const row of rows) {
    parts.push(
      `\n-- ---------------------------------------------------------------------------\n` +
        `-- ${row.label}\n` +
        `-- ---------------------------------------------------------------------------\n\n`,
    );
    parts.push(`${row.definition.trim().replace(/;$/, "")};\n`);
  }

  return parts.join("");
}

/**
 * Keeps only migration-like DDL from a full pg_dump: enums, tables, views,
 * constraints, foreign keys, indexes, RLS enablement, and policies.
 * Drops functions, triggers, comments, and dump preamble.
 * @param {string} dump
 * @returns {string}
 */
function filterSchemaDump(dump) {
  const lines = dump.split("\n");
  /** @type {string[]} */
  const keptSections = [];
  /** @type {string[]} */
  let currentSection = [];
  /** @type {string | null} */
  let currentType = null;
  let inSection = false;

  /**
   * Flushes the current section when it matches an allowed object type.
   */
  const flushSection = () => {
    if (currentType && SCHEMA_OBJECT_TYPES.has(currentType)) {
      // Drop pg_dump's trailing footer if it landed on the last section.
      const completeIdx = currentSection.findIndex((sectionLine) =>
        sectionLine.includes("PostgreSQL database dump complete"),
      );

      if (completeIdx >= 0) {
        currentSection = currentSection.slice(0, completeIdx);

        while (currentSection.at(-1) === "" || currentSection.at(-1) === "--") {
          currentSection.pop();
        }
      }

      const body = currentSection.join("\n").trim();

      if (body.length > 0) {
        keptSections.push(body);
      }
    }

    currentSection = [];
    currentType = null;
    inSection = false;
  };

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i] ?? "";
    const headerMatch = line.match(PG_DUMP_SECTION_HEADER_RE);

    if (headerMatch) {
      // Opening `--` of this section was already pushed onto the previous one.
      if (inSection && currentSection.at(-1) === "--") {
        currentSection.pop();

        while (currentSection.at(-1) === "") {
          currentSection.pop();
        }
      }

      flushSection();

      currentType = headerMatch[1] ?? null;
      inSection = true;
      currentSection = ["--", line];
      continue;
    }

    if (!inSection) {
      continue;
    }

    currentSection.push(line);
  }

  flushSection();

  return keptSections.join("\n\n") + (keptSections.length > 0 ? "\n" : "");
}

/**
 * Dumps public schema DDL via pg_dump (enums, tables, views, constraints,
 * foreign keys, indexes, RLS policies). Functions/triggers stay in their own
 * files.
 * @param {string} databaseUrl
 * @returns {string}
 */
function dumpPublicSchema(databaseUrl) {
  try {
    const dump = execFileSync(
      "pg_dump",
      [...SCHEMA_DUMP_ARGS, databaseUrl],
      { encoding: "utf8" },
    );

    const filtered = filterSchemaDump(dump);

    return `${GENERATED_HEADER}\n${filtered}`;
  } catch (error) {
    const detail =
      error instanceof Error && "stderr" in error && error.stderr
        ? String(error.stderr).trim()
        : error instanceof Error
          ? error.message
          : String(error);

    throw new Error(
      "Failed to dump public schema with pg_dump.\n" +
        "Ensure pg_dump is on PATH and matches the local Supabase Postgres major version.\n" +
        detail,
    );
  }
}

/**
 * Exports public schema DDL plus non-extension public functions and
 * public/auth triggers.
 */
async function main() {
  const databaseUrl =
    process.env.DATABASE_URL ??
    process.env.SUPABASE_DB_URL ??
    DEFAULT_DATABASE_URL;

  const client = new pg.Client({ connectionString: databaseUrl });

  try {
    await client.connect();
  } catch (error) {
    console.error(
      "Failed to connect to local Supabase Postgres.\n" +
        "Start the stack with `pnpm supabase:start` (or `pnpm dev`), then retry.\n" +
        `URL: ${databaseUrl}`,
    );
    throw error;
  }

  try {
    const [functionsResult, triggersResult] = await Promise.all([
      client.query(FUNCTIONS_QUERY),
      client.query(TRIGGERS_QUERY),
    ]);

    const schemaSql = dumpPublicSchema(databaseUrl);

    const functionsSql = buildSqlDump(
      functionsResult.rows.map((row) => ({
        label: `${row.name}(${row.args})`,
        definition: row.definition,
      })),
    );

    const triggersSql = buildSqlDump(
      triggersResult.rows.map((row) => ({
        label: `${row.schema_name}.${row.table_name}.${row.name}`,
        definition: row.definition,
      })),
    );

    mkdirSync(OUTPUT_DIR, { recursive: true });
    writeFileSync(SCHEMA_PATH, schemaSql, "utf8");
    writeFileSync(FUNCTIONS_PATH, functionsSql, "utf8");
    writeFileSync(TRIGGERS_PATH, triggersSql, "utf8");

    const tableCount = (schemaSql.match(/^CREATE TABLE\b/gm) ?? []).length;
    const viewCount = (schemaSql.match(/^CREATE(?: OR REPLACE)? VIEW\b/gm) ?? [])
      .length;
    const indexCount = (
      schemaSql.match(/^CREATE(?: UNIQUE)? INDEX\b/gm) ?? []
    ).length;
    const policyCount = (schemaSql.match(/^CREATE POLICY\b/gm) ?? []).length;

    console.log(
      `Exported schema (${tableCount} tables, ${viewCount} views, ${indexCount} indexes, ${policyCount} policies) → db/sql/schema.sql`,
    );
    console.log(
      `Exported ${functionsResult.rows.length} functions → db/sql/functions.sql`,
    );
    console.log(
      `Exported ${triggersResult.rows.length} triggers → db/sql/triggers.sql`,
    );
  } finally {
    await client.end();
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
