/**
 * Cloudflare Workers entry point (see wrangler.jsonc `main`).
 *
 * The worker generated by `opennextjs-cloudflare build` only exports `fetch`.
 * This wrapper re-exports it and adds the Cloudflare Queues consumer for the
 * Meta scrape pipeline, which hands every message to the Next.js queue route
 * in-process (no network hop) and acks/retries based on the response.
 *
 * Typed structurally because the global `@cloudflare/workers-types` conflict
 * with the DOM lib used by the Next.js app.
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as openNextHandler } from "./.open-next/worker.js";

import {
  consumeMetaScrapeBatch,
  type QueueBatchLike,
} from "./src/lib/meta/cloudflare-queue-consumer";

const LOCAL_ORIGIN = "http://localhost";

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

const worker = {
  fetch: openNextHandler.fetch,

  async queue(
    batch: QueueBatchLike,
    env: CloudflareEnv,
    ctx: WorkerExecutionContext,
  ): Promise<void> {
    await consumeMetaScrapeBatch(batch, {
      secret: env.META_SCRAPES_QUEUE_SECRET,
      origin: env.APP_URL ?? LOCAL_ORIGIN,
      fetch: (request) => openNextHandler.fetch(request, env, ctx),
    });
  },
};

export default worker;

// Required by OpenNext when the DO queue / sharded tag cache overrides are used.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
